### ISSUE TITLE
Selecting other destination for the full sync freezes the setup screen

### ISSUE THREAD

**Issue by Barraguesh** [flathub/nz.mega.MEGAsync#1]
In my Fedora 33 machine, when selecting another folder, the program crashes and freezes, not changing the selected folder. I personally backup my whole home and freezes even when the sandbox has access to the directory (given through Flatseal). Selecting another folder like Downloads gives the same result. Fresh install.

**Comment by Barraguesh** [comment]
This screen ![image](https://user-images.githubusercontent.com/25356150/102703326-4a438080-4265-11eb-9694-fc97c369bdf4.png)

**Comment by tim77** [comment]
Platform-native file dialog was enabled intentional for debugging purposes (https://github.com/flathub/nz.mega.MEGAsync/commit/2d9dcdf79c60cf7ad03d74f877b4d7fb71cc9809) but since there is no progress with fixing this issue - reverting back. Now for custom locations you need to add manually permission to app first (Flatseal easy way to do this). Thanks for reporting.

**Comment by Barraguesh** [comment]
I have enabled full host access or even the top folder to the one I wanna use access and still didn't work.

**Comment by tim77** [comment]
Package not built and updated, sorry. Something wrong with `gnutls_handshake` `libsodium` module https://github.com/flathub/flathub/issues/2008
If you hurry up with update you need to rebuilt Mega manually. Just take latest build from master branch. Build failure related to builder, not MEGAsync package itself.

**Comment by Barraguesh** [comment]
Any progress on this issue? I am using the RPM version for now. Also I am available as a developer if any debbuging/help is needed.

**Comment by tim77** [comment]
So this latest [build](https://flathub.org/builds/#/builders/32/builds/35172) still doesn't work for you? Weird. After disabling platform-native file dialog i can pick any dir without this hang but before need to allow such dirs via Flatseal for sure.

**Comment by Barraguesh** [comment]
I am so sorry I didn't mean that it didn't work, I wanted to know the status because I haven't tried it yet (as I said I am using the RPM version). Will try later and then update.

**Comment by Barraguesh** [comment]
Sorry for the late reply, was busy. I tested it again and works flawlessly!

**Comment by tim77** [comment]
Nice to hear. Thank you for testing. This is not :100: solution but at least it works. Would be nice to fix portals in future but better to track "portal" bug/feature in separate issue. Now we can closing this one.
