### ISSUE TITLE
[Bug] Creation of folders at each app launch, even if not used

### ISSUE THREAD

**Issue by Delan168** [flathub/nz.mega.MEGAsync#16]
By default, the app uses the folders `~/MEGA` and `~/MEGAsync Downloads` for the storage, and a folder `~/MEGAsync` (why? it remains empty...).
I chose to store my sync folders elsewhere (in `~/Cloud`) to keep my home directory tidy. I gave access to these folders to MEGAsync through `sudo flatpak override nz.mega.MEGAsync --filesystem="$HOME/Cloud/MEGA/"` and `sudo flatpak override nz.mega.MEGAsync --filesystem="$HOME/Cloud/MEGAsync Downloads/"` (source: https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory) and defined those synced directories in the app settings. It works fine.

However the three folders `~/MEGA`, `~/MEGAsync Downloads` and `~/MEGAsync` keep being created at every app launch, even if they are not used. How can I disable this behaviour?

Note: I used to have the app through AUR (I run Manjaro), I did not had to reconfigure the credentials, but I had to reconfigure the folders used. 
Note 2: I did not had this behaviour with the AUR version, however I wanted to swtich from AUR to Flatpak to avoid the lengthy recompiling at every update.

**Comment by tim77** [comment]
You [shouldn't](https://github.com/flathub/nz.mega.MEGAsync/pull/3#issuecomment-812837707) changing this default behavior and there is no problem if these folders existing.
