### ISSUE TITLE
Flathub version is outdated

### ISSUE THREAD

**Issue by SayanChakroborty** [flathub/nz.mega.MEGAsync#28]
Latest version is 4.6.8.0 while flathub version is 4.6.7.0 although I don't see 4.6.8.0 Linux release on releases page of megasync github repository but the native debian package along with all available Linux packages are currenly 4.6.8.0.

**Comment by tim77** [comment]
Hello. `4.6.7.0` is latest Linux version of MEGAsync. Upstream usually lags with Linux releases and this is normal. But you can always clarify and ask this upstream.

**Comment by SayanChakroborty** [comment]
> Hello. `4.6.7.0` is latest Linux version of MEGAsync. Upstream usually lags with Linux releases and this is normal. But you can always clarify and ask this upstream.

Latest Linux version is `4.6.8.0` as you can see [here](https://mega.nz/linux/repo/). Look into any Linux distribution directory on that page and you'll find that the package is indeed `4.6.8.0`.

It might seem rude to hurry an update where upstream has not yet _released_ the update in their github page (although latest native packages have been updated at least a couple weeks ago) but `4.6.7.0` (the latest version in flathub) is [broken since a long time](https://github.com/flathub/nz.mega.MEGAsync/issues/18) and it may get fixed with the new update. Currently the only way to not have a broken installation is to avoid flatpak which is not great as flatpak has its own use cases.

Now I don't know if updating will fix the issue #18 and I also don't know the update procedure for flatpak, like do you update the flatpak version after the github release of upstream or you just take the released binary and repackage it as flatpak?
