### ISSUE TITLE
flathub version is outdated again

### ISSUE THREAD

**Issue by edmundlaugasson** [flathub/nz.mega.MEGAsync#35]
if to look at https://mega.io/linux/repo/Arch_Extra/x86_64/ then you see already v4.7.2 of megasync is out currently
also I hope there will be filemanager integration - there are available also those packages

**Comment by tim77** [comment]
Flathub version is not outdated again. For transparency Flathub build using github MEGAsync repo, not https://mega.io/linux/repo/Arch_Extra/. Upstream not making Linux tags on github again and force-pushing tags, you can see this by flathubbot PR [history](https://github.com/flathub/nz.mega.MEGAsync/pulls?q=Update+MEGAsync.git). Please report this upstream next time.

**Comment by edmundlaugasson** [comment]
Sorry but if you look at https://flathub.org/apps/details/nz.mega.MEGAsync then you see version 4.6.8 but already 4.7.2 is out and certainly versions between those two numbers. Definitely is newer MegaSync out than currently in Flatpak - so, actually it is outdated. I don't know your internal work arrangements - I am not developer. I don't know, what or who you mean by "upstream". I see, that Flatpak package is outdated and still not updated, so I reported. Just closing report does not update the package itself. Very sad, that still not updated.

**Comment by edmundlaugasson** [comment]
now is at Flatpak also 4.7.2 - when I checked, was 4.6.8 - thank you for updating
Arch packages tend to be also outdated sometimes
