### ISSUE TITLE
Missing filesystem permission

### ISSUE THREAD

**Issue by inorick** [flathub/nz.mega.MEGAsync#4]
The current filesystem permissions do not allow access to the folder `~/MEGAsync`. This is the folder that is used on a fresh install when using selective sync. The client will still start to sync but the files will not be transferred to the expected directory due to missing permissions.

I created #3 to fix this. Note that the PR drops the old permissions for the `~/MEGA` folder as I am not sure if it is used by the client at all.

**Comment by tim77** [comment]
Fixed in dd6103d9371353bf1ad78c0e5e7584f1ee5ee28b. Thank you.
