### ISSUE TITLE
Summary shouldn't end with a fullstop

### ISSUE THREAD

**Issue by razzeee** [flathub/nz.mega.MEGAsync#46]

**Comment by tim77** [comment]
Hello @razzeee The same here: please submit and discuss this changes with upstream. Upstream should at least aware about downstream changes which they may not like. 

I was guided only by the fact that I copied the original and have no right to change the description or something else. But your proposal is more only grammatical changes, so I think there will be no problems here.

Would you like to submit a PR [here](https://github.com/meganz/MEGAsync/pull/510)? Or I will update my PR as i can.

**Comment by razzeee** [comment]
I think changing your pr makes the most sense
