### ISSUE TITLE
Package lagging behind due to missing upstream tags

### ISSUE THREAD

**Issue by slagiewka** [flathub/nz.mega.MEGAsync#47]
Just want to raise the issue so that maybe someone updates it manually.

Reported upstream https://github.com/meganz/MEGAsync/issues/821.

Since no tag exist, I wasn't sure if submitting a PR with update to commit only (and maybe faking the tag) would be OK with this package's maintainers. Or if it would work at all, for that matter.

**Comment by tim77** [comment]
https://github.com/flathub/nz.mega.MEGAsync/issues/28
