### ISSUE TITLE
Unresponsive when adding Sync Folders

### ISSUE THREAD

**Issue by abuturabofficial** [flathub/nz.mega.MEGAsync#49]
I can login fine, but the app becomes unresponsive when adding the `sync folders`. The app will remain in the same state for an indefinite period of time, until from the tray/system monitor you quit/kill it. No matter how long you wait, it neither adds sync folders nor get out of freezing state or crash.

All these issues started with latest update of `4.9.5.0_OSX`.

**Comment by GrgMdmn** [comment]
I have the same problem: I can confirm. Too bad, the flatpak version is the only one that has the rights to browse different storage drives.

**Comment by mardab** [comment]
Can confirm, this update replaces built-in file selector with one from system, and that does not translate well between system and flatpak, thus causes lockup no matter whether you select something or cancel.

Here is a handy downgrade command back to one before latest:
`# flatpak update --commit=7f30d8f2998e3376afb64525ae537f392c7b737b6209a13fc29a1610493f418c nz.mega.MEGAsync`

**Comment by abuturabofficial** [comment]
> Can confirm, this update replaces built-in file selector with one from system, and that does not translate well between system and flatpak, thus causes lockup no matter whether you select something or cancel.
> 
> Here is a handy downgrade command back to one before latest: `# flatpak update --commit=7f30d8f2998e3376afb64525ae537f392c7b737b6209a13fc29a1610493f418c nz.mega.MEGAsync`

Thanks a lot, I didn't know that method for downgrade.

**Comment by abuturabofficial** [comment]
> The downgrade does not help much as it does not show any folders except the ones MegaSync created: MEGA and MEGAsync. Do I have to sync into these folders or shouln't I because they contain internal data?

Add required folders' permissions via flatseal (it used to work that way, now I don't use flatpak version anymore)

**Comment by JPT77** [comment]
Yeah, sure. Thanks. Should help.
Flatseal is not really user friendly, but somehow it does it's job.

**Comment by abuturabofficial** [comment]
@DinoMC Please consider using native package for your distribution or distrobox (if on some immutable distro), as flatpak version of `megasync` is very slow in upgrading to the latest release, and it may cause a security issue.

**Comment by abuturabofficial** [comment]
@danieltomasz maybe try their `.deb` package instead of building from source for the time, issue is being fixed.
