### ISSUE TITLE
Build MEGAShellExtNautilus

### ISSUE THREAD

**Issue by teohhanhui** [flathub/nz.mega.MEGAsync#5]
The project file: https://github.com/meganz/MEGAsync/blob/6114a136b6ef1eb681f2d38373907a156a1dcfaa/src/MEGAShellExtNautilus/MEGAShellExtNautilus.pro

From https://github.com/meganz/MEGAsync/issues/576

**Comment by tim77** [comment]
How would you imagine this should work with **host** Nautilus? This is not possible to do in current state for ftatpak build until Mega upstream adopt it via d-bus for example.

**Comment by teohhanhui** [comment]
Looks like it should be possible to install the shell extension in the home directory under `~/.local/share/flatpak/exports/share/nautilus-python/extensions` since `~/.local/share/flatpak/exports/share` is in `$XDG_DATA_DIRS`

**Comment by teohhanhui** [comment]
I guess it needs to be supported in Flatpak itself similar to `share/gnome-shell/search-providers`?

https://github.com/flatpak/flatpak/blob/686af7d3b81b1315256e79eb5991cede458f3498/app/flatpak-builtins-build-finish.c#L237

**Comment by teohhanhui** [comment]
Opened https://github.com/flatpak/flatpak/issues/4323

**Comment by teohhanhui** [comment]
What about building the extension in this flatpak, and then the user can manually create a symlink? That should work, right?
