### ISSUE TITLE
Is this still maintained? It's outdated, using end-of-life libraries.

### ISSUE THREAD

**Issue by Rantyrant** [flathub/nz.mega.MEGAsync#57]
This is now 2 versions behind upstream (v4.10.0.0 https://github.com/meganz/MEGAsync/releases/tag/v4.10.0.0_OSX), and using end-of-life libraries (org.kde.Platform 5.15-21.08, and org.freedesktop.Platform.GL.default 21.08).

**Comment by tim77** [comment]
https://github.com/flathub/nz.mega.MEGAsync/pull/27#issuecomment-1246025856
