### ISSUE TITLE
Switch to official repos as source

### ISSUE THREAD

**Issue by bbhtt** [flathub/nz.mega.MEGAsync#62]
It seems like Mega for some time have stopped tagging Linux tags on Github but the official repository continues to have precompiled distro binaries and distro source packages. See https://github.com/meganz/MEGAsync/issues/821

Will it be possible to switch to that and update to 4.11.0?

https://mega.nz/linux/repo/Debian_12/

https://mega.nz/linux/repo/Fedora_39/src/

Somone reported in #flatpak that this might fix a crash with the current published version.

**Comment by tim77** [comment]
Thanks for reporting. This is never ending [story](https://github.com/meganz/MEGAsync/issues/647) and this happens every new Mega release. Upstream usually tag new Linux versions after some delay. Report and remind [here](https://github.com/meganz/MEGAsync/issues) also helpful. I still haven’t lost hope that one day upstream will officially start maintaining Flathub build.

**Comment by bbhtt** [comment]
I commented on the upstream issue linked in OP. I wouldn't mind if you close this and wait for a GitHub release.

This issue was opened because the person experiencing the crash didn't have a github account and wanted update to 4.11.0. They weren't also sure if the update would fix the crash and couldn't share and info related to the crash.

**Comment by tim77** [comment]
Please test [new](https://github.com/flathub/nz.mega.MEGAsync/pull/63#issuecomment-1833753595) 4.11.0 version.

**Comment by bbhtt** [comment]
The user confirmed that 4.11.0 fixed their issue, I'm closing this as it is not viable to switch to official repos for reasons mentioned above.
