### ISSUE TITLE
runtime org.kde.Platform branch 5.15-21.08 is end-of-life

### ISSUE THREAD

**Issue by superuser-miguel** [flathub/nz.mega.MEGAsync#66]
Info: runtime org.kde.Platform branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   nz.mega.MEGAsync

any possibility this can be updated soon?

**Comment by tim77** [comment]
Hello! Please check https://github.com/flathub/nz.mega.MEGAsync/pull/27 Help with testing wanted.
