### ISSUE TITLE
Keep freeze. Please downgrade to stable version

### ISSUE THREAD

**Issue by nhannht** [flathub/nz.mega.MEGAsync#76]
The problem in this [issue](https://github.com/flathub/nz.mega.MEGAsync/issues/49) is still the same. Freeze GUI when clicking on local files with native file chooser. The app cannot access the local folder when downloaded. I am using RHEL 9. 

I suggest better downgrading the version in Flatpak to 4.7.3.0. Stable is more important than the bleeding edge but keeps making users frustrated

**Comment by nhannht** [comment]
I don't have the meaning to blame you or demand you to do something. Thank you for your great work and I just want to suggest some things I thought were good.

When wrapping an application around Flatpak, it is normal to expect some tradeoffs. But at least  the apps from Flatpak will function as they expected without required extra tweaks. You could add some document tips, instead of making many people confused when things keep broken. I also note that there are only a few people like you have knowledge about Flatpak/MegaSync to fix the problem.

**Comment by tim77** [comment]
[Pinned issue](https://github.com/flathub/nz.mega.MEGAsync/issues/13). Maybe we also should document this on README-flathub file. Would be really great if upstream help with this issue and do a proper fix. Upstream bug could tracked there https://github.com/meganz/MEGAsync/issues/841
